/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}"
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#fff1ed",
        "surface": "#fff8f6",
        "inverse-on-surface": "#ffede9",
        "secondary-fixed-dim": "#ffb2bc",
        "secondary-fixed": "#ffd9dd",
        "on-background": "#271814",
        "color-status-success-dark": "rgba(200, 220, 192, 0.2)",
        "surface-variant": "#f9dcd5",
        "error-container": "#ffdad6",
        "on-primary-container": "#fffbff",
        "secondary": "#aa314d",
        "inverse-primary": "#ffb4a2",
        "surface-dim": "#f0d4cd",
        "on-primary-fixed": "#3c0800",
        "tertiary": "#00609b",
        "color-text-primary-light": "#2C2B27",
        "color-status-info": "#0284C7",
        "surface-tint": "#b32a00",
        "color-text-secondary-dark": "rgba(244, 243, 239, 0.8)",
        "background": "#fff8f6",
        "outline": "#8f7068",
        "color-status-error": "#DC2626",
        "error": "#ba1a1a",
        "surface-container-high": "#ffe2db",
        "color-bg-deep-light": "#EEEDE8",
        "secondary-container": "#f96d87",
        "on-secondary-container": "#6c0024",
        "primary-container": "#d63c11",
        "color-bg-primary-dark": "#18181B",
        "color-action-cta": "#E8491E",
        "primary": "#af2900",
        "primary-fixed-dim": "#ffb4a2",
        "color-text-secondary-light": "#706F6B",
        "surface-bright": "#fff8f6",
        "color-status-success-light": "#C8DCC0",
        "tertiary-fixed": "#d0e4ff",
        "on-tertiary-container": "#fdfcff",
        "on-secondary-fixed": "#400012",
        "primary-fixed": "#ffdbd2",
        "color-status-warning": "#D97706",
        "on-tertiary-fixed": "#001d34",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "color-bg-surface-light": "#FFFFFF",
        "color-bg-deep-dark": "#111111",
        "on-secondary-fixed-variant": "#8a1736",
        "on-tertiary-fixed-variant": "#004a79",
        "on-surface": "#271814",
        "surface-container": "#ffe9e4",
        "surface-container-highest": "#f9dcd5",
        "color-bg-surface-dark": "#1F2937",
        "on-primary-fixed-variant": "#891e00",
        "color-emotion-like": "#E8607A",
        "color-divider-dark": "rgba(255, 255, 255, 0.05)",
        "tertiary-container": "#0079c3",
        "surface-container-lowest": "#ffffff",
        "color-text-primary-dark": "#F4F3EF",
        "on-error": "#ffffff",
        "inverse-surface": "#3e2c28",
        "color-divider-light": "rgba(0, 0, 0, 0.05)",
        "outline-variant": "#e4beb5",
        "color-bg-primary-light": "#F4F3EF",
        "on-surface-variant": "#5b403a",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#9bcbff",
        "on-primary": "#ffffff"
      },
      spacing: {
        "space-1": "4px",
        "space-2": "8px",
        "space-3": "12px",
        "space-4": "16px",
        "space-5": "24px",
        "space-6": "32px",
        "space-8": "48px"
      }
    },
  },
  plugins: [],
}
